package org.example.cli.server;

public enum Option {
    //Admin options
    CREATE_USER, CREATE_COURSE, UPDATE_USER, UPDATE_COURSE, DELETE_USER, DELETE_COURSE, VIEW_USERS, VIEW_COURSES, ASSIGN_INSTRUCTOR,
    //Instructor options
    ENROLL_STUDENT, REMOVE_STUDENT, REMOVE_ASSESSMENT, CREATE_ASSESSMENT, UPDATE_ASSESSMENT, VIEW_ASSESSMENTS, GRADE_ASSESSMENT, VIEW_INSTRUCTOR_COURSES,
    //Student options
    VIEW_STUDENT_COURSES, VIEW_STUDENT_GRADES, VIEW_STUDENT_ASSESSMENTS

}
